name: Build on Commit

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'

      - name: Install dependencies
        run: rm -rf node_modules/ && npm install

      - name: Compile TypeScript
        run: tsc
